services:
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3001"
    environment:
      - MB_DB_TYPE=mysql
      - MB_DB_DBNAME=metabase_db
      - MB_DB_PORT=3306
      - MB_DB_USER=metabase_user
      - MB_DB_PASS=secure_password
      - MB_DB_HOST=mysql
    depends_on:
      - mysql
    volumes:
      - metabase-data:/metabase-data

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: metabase_db
      MYSQL_USER: metabase_user
      MYSQL_PASSWORD: secure_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  metabase-data:
  mysql-data:
